// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2;

#nullable disable

namespace P2.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20220605225845_SeatSlots")]
    partial class SeatSlots
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("P2.Model.Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("TrainId");

                    b.ToTable("Departures");
                });

            modelBuilder.Entity("P2.Model.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("P2.Model.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("P2.Model.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("P2.Model.TrainLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SourceId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("P2.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P2.Model.Departure", b =>
                {
                    b.HasOne("P2.Model.TrainLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId");

                    b.HasOne("P2.Model.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId");

                    b.Navigation("Line");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("P2.Model.Seat", b =>
                {
                    b.HasOne("P2.Model.Train", null)
                        .WithMany("Seating")
                        .HasForeignKey("TrainId");

                    b.OwnsMany("P2.Model.Slot", "Slots", b1 =>
                        {
                            b1.Property<int>("SeatId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Col")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Row")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SeatNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SeatType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SeatId", "Id");

                            b1.ToTable("Slot");

                            b1.WithOwner()
                                .HasForeignKey("SeatId");
                        });

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("P2.Model.TrainLine", b =>
                {
                    b.HasOne("P2.Model.Station", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("P2.Model.Station", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.OwnsMany("P2.Model.Stop", "Stops", b1 =>
                        {
                            b1.Property<int>("TrainLineId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Price")
                                .HasColumnType("REAL");

                            b1.Property<int?>("StationId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TrainLineId", "Id");

                            b1.HasIndex("StationId");

                            b1.ToTable("Stop");

                            b1.HasOne("P2.Model.Station", "Station")
                                .WithMany()
                                .HasForeignKey("StationId");

                            b1.WithOwner()
                                .HasForeignKey("TrainLineId");

                            b1.Navigation("Station");
                        });

                    b.Navigation("Destination");

                    b.Navigation("Source");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("P2.Model.Train", b =>
                {
                    b.Navigation("Seating");
                });
#pragma warning restore 612, 618
        }
    }
}
